apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loadgen-data
  namespace: demo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 100Mi
